### ISSUE TITLE
:key property is not passed to react

### ISSUE THREAD

**Issue by ul** [levand/quiescent#29]
Inspecting DOM running [TodoMVC example](https://github.com/levand/todomvc/blob/gh-pages/architecture-examples/quiescent/src/todomvc_quiescent/render.cljs) shows that `:key` property of `Item` component is not used by React. The same behaviour I noticed using quiescent in my project.

Changing [here](https://github.com/levand/quiescent/blob/master/src/quiescent.cljs#L46)
`(react-component #js {:value value :statics static-args})` to `(react-component #js {:value value :statics static-args :key (:key value)})` and passing `:key` in component data forces it to be used, but this is not right fix, I guess.

M.b. I'm doing something wrong, and this is not quiescent issue?

**Comment by levand** [comment]
This is fixed in master - you can now specify a `:keyfn` in a component's [options map](https://github.com/levand/quiescent/blob/master/docs.md#component-options) that will calculate a key based off the given value.
