### ISSUE TITLE
Documentation about maintaining zero local state

### ISSUE THREAD

**Issue by slorber** [levand/quiescent#31]
`
Om explicitly allows components to maintain local state, while Quiescent forbids this. In my opinion the benefits of requiring components to account for local state do not justify the pervasive cost to implementation.
`

I kind of agree with this but would like to have a clarification.

Are there exceptions?
How do you handle text inputs in quiescent? Do you update the global appState in each key event and trigger a full re-render? 

Do you have good practices/design patterns references to handle all the application state outside of React (particularly async/remote data)? or is it leaved to the implementor?

**Comment by levand** [comment]
I do have some examples of using Quiescent to drive a third-party, stateful component (e.g, an interactive D3 visualization).

I definitely want to bring this use case to the front and center with the next release of Quiescent, including some helpers that will lead users down the path of how to do this. It's become apparent to me that it's an important element of just about any Quiescent app.
