### ISSUE TITLE
Managing a controlled TextArea component.

### ISSUE THREAD

**Issue by samedhi** [levand/quiescent#32]
I have a controlled TextArea component. As per quiescents philosophy, in my on-change event handler for this component, I update the top level state atom, rather than having any local state. Updating this atom causes my quiescent flow to re-render. This does appear to work, however, I have noticed two behaviors that have me concerned.

1) the "value" attribute of the DOM element matching the TextArea component is not updating with the updated value in the text area. I am not sure whether this is expected behavior. The documentation http://facebook.github.io/react/docs/forms.html under "controlled components" does not make it clear whether the state value at this.state.value should also update the dom "value" attribute in sync? Either way, since I am basically setting the "value" attribute by setting the single root atom, I would think that the "value" would update, but this does not seem to be the case.

2) The TextArea has its cursor set to the end of the text every time it is edited. This makes it rather difficult to actually edit anything but the last character in the TextArea.

Does anyone have any examples of using a controlled textarea (or input) component with quiescent? Have you gotten it to work? Any help is appreciated, thanks.

**Comment by levand** [comment]
Sorry for the long turnaround time on this. There is now a fix for it in master, though you'll have to use one of the new uncontrolled inputs

See the documentation at https://github.com/levand/quiescent/blob/master/docs.md#cursor-jumping-and-controlled-inputs
