### ISSUE TITLE
controlled input caret jumps to end when input is modified

### ISSUE THREAD

**Issue by dustingetz** [levand/quiescent#36]
Here is a [demo repo with reduced test case](https://github.com/dustingetz/quiescent-controlled-input-caret-bug).

The [final commit](https://github.com/dustingetz/streaker/commit/9c11a608721133b8759fdc48beb467ec991969e2) in this repo fixes the bug via the [react-async-input monkey patch described here](https://github.com/grncdr/react-async-input).

Uncomment the monkey patch on line 13 of index.html to see the broken behavior.

**Comment by levand** [comment]
Sorry for the long turnaround time on this. There is now a fix for it in master, though you'll have to use one of the new uncontrolled inputs

See the documentation at https://github.com/levand/quiescent/blob/master/docs.md#cursor-jumping-and-controlled-inputs
