### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by jdeisenberg** [levand/quiescent#42]
At `quiescent/docs.md` in the section titled "Rendering", this code

    (render (Hello {:fname "Ned" :lname "Stark"}
               (.getElementById js/document "hello-div")))

Should be

    (q/render (Hello {:first-name "Ned" :last-name "Stark"})
               (.getElementById js/document "hello-div"))

Also, for consistency, the preceding section's `defcomponent` should be `q/defcomponent`

**Comment by levand** [comment]
Thanks, I'll fix this next time I'm updating the docs.

**Comment by levand** [comment]
Actually, I think this is fine as-is. This is a small context-less snippet, and the surrounding prose clearly indicates that the `render` function belongs in the `quiescent.core` namespace. 

If I changed this snippet, I would want to change *all* the snippets in the examples to use namespaces pervasively, and I think that would hurt their clarity. 

Thanks for the feedback, though! I'll keep this in mind for future documentation, to avoid this type of confusion as best I can.
