### ISSUE TITLE
Add new SVG tags introduced in 0.13.3

### ISSUE THREAD

**Issue by sodiumjoe** [levand/quiescent#43]
I'm working on a component that uses the svg `<defs>` and `<clipPath>` tags, which aren't availble before 0.13.3. I'd be happy to try to dig in myself, but want to make sure I'm not duplicating someone else's work.

**Comment by levand** [comment]
This is pretty easy to do, the only thing that should be required is to add them to the list of tags here: https://github.com/levand/quiescent/blob/release/src/quiescent/dom.cljs#L6

Noone else is working on it that I'm aware of, feel free to submit a PR.

**Comment by Will-Sommers** [comment]
Hi @levand I'd like to take a crack at this. Will try to have a PR up this weekend/next week.

**Comment by levand** [comment]
Awesome, thanks.

**Comment by levand** [comment]
Fixed in fab15ae74442db63169cd81e95d38e372a23acf0
