### ISSUE TITLE
Example of ReactCSSTransitionGroup?

### ISSUE THREAD

**Issue by monjohn** [levand/quiescent#44]
I was wondering if anyone had an example of using ReactCSSTransitionGroup. I see that there was one referenced in issue #19, but couldn't get it to work. Plus, it seems like the problem raised in that issue has been fixed.

**Comment by jraines** [comment]
There is an example in the repo here:

https://github.com/levand/quiescent/blob/release/examples/css-animations/src/css_animations.cljs

However, I'm also having trouble getting that one to work.

my code looks like this:

```clojure
q/defcomponent SmallItem
                :did-enter  #(println "did enter")
                :will-enter #(println "will enter")
                :did-leave  #(println "did-leave")
                :keyfn      #(:id %)
                [item]
                (d/div {:className "small-item-wrapper example-enter"}
                  (d/div {:className "small-item"
                          :style (small-item-css item)}
                         "")))

;;code in containing component omitted...
(d/div {:id "replacements"}
                         (apply q/CSSTransitionGroup
                                {:transitionName "example"}
                                (map SmallItem replacements)))))
```

Only the first small item ever animates in.  I never see any others as I add them, and they aren't in the DOM.  The keyfn is getting called for every item (including the ones that never show), and it is returning unique, consistent values for them.  None of the other hooks are ever called, even for the first one that does animate in.

**Comment by jraines** [comment]
I was able to fix mine by changing the second part, removing the apply:

```
(d/div {:id "replacements"}
                         (q/CSSTransitionGroup
                              {:transitionName "example"}
                              (map SmallItem replacements)))))
```

**Comment by jraines** [comment]
One final note (per my possibly flawed understanding):  Until React 0.14 is released, then added to cljs, then pulled in as a dep to quiescent, you *must* define a transition (by adding .example-leave-active{...} in your CSS) for the children leaving the transition group.  If you just try to set {:transitionLeave false}, you will hit this bug: https://github.com/facebook/react/pull/2549

**Comment by levand** [comment]
Closing, since it seems like this issue is resolved? At any rate, let me know if there need to be any changes here.
