### ISSUE TITLE
Development Status

### ISSUE THREAD

**Issue by yeehaa123** [levand/quiescent#48]
Is Quiescent still be under active development, or has this project been abandoned? I am considering a switch from reagent, but I want to know if there are any plans of moving this project forward.

**Comment by zentrope** [comment]
I'm really liking this minimalist approach for a lot of things I work on. I hope you keep going with it!

**Comment by shyblower** [comment]
+1 ... in my opinion this is the best available approach for bringing React to Clojurescript. And it's the only one I know that lets me decide when to render my data. Look at the example here https://github.com/shyblower/clonut to see what I mean.

**Comment by zentrope** [comment]
I'm using Sablono now with quiescent, but it's most recent version expects React 0.14. Any chance of a clojars release with that version in it?

**Comment by zentrope** [comment]
Dependencies like this:

```clojure
   [quiescent "0.2.0-RC2" :exclusions [cljsjs/react-with-addons]]
   [cljsjs/react-with-addons "0.14.3-0"]
   [cljsjs/react-dom "0.14.3-1" :scope "provided"]
   [cljsjs/react-dom-server "0.14.3-0" :scope "provided"]
   [sablono "0.5.0"]
```

while it compiles seems to have caused my app to endlessly cycle as if attempting to render a nil component, or something like that.

**Comment by zentrope** [comment]
Seems to have something to do with the CSSTransitionGroup. Anyway, alas, seems this project is living up to its name.

**Comment by zentrope** [comment]
I forked and fixed. ;) Seems you need to include ReactDOM and change .render and a few others to (js/ReactDOM.render ...) and it works. Didn't solve the CSSTransitionGroup thing, but then I don't use it.
